<!DOCTYPE HTML>
<html>
 <head>
  <meta charset="utf-8">
  <title>XYZ: СОБ - %title%</title>
  <style>
   body {
    background-color: #DEDECA;
   }
   h1 { 
    font-family: Arial; 
    font-size: 1.8em; 
    color: #630; 
   }
   h3 { color: #963; }
   a { color: #360; }
   a:link {color: #360; text-decoration: none;}
   a:visited {color: #360; text-decoration: none;}
   a:hover {text-decoration: underline;}
.listtab
   td { border-bottom: #333 1px dashed; padding: 3px; font-size: 10pt;}
  </style>
</head>
<body><table><tr>
   <td><img src="/XYZ/logo.jpg" /></td>
   <td valign="top"><h1>XYZ: Система Обеспечения Безопасности</h1>
    <h2>%h2%</h2>
    <h3>%h3%</h3>
   </td>
 </tr>
 </table>
